Improve the shrinkpdf snippet
This commit adds a check for installed prerequisites plus a few
shellcheck fixes.

diff --git a/shrinkpdf b/shrinkpdf
--- a/shrinkpdf
+++ b/shrinkpdf
@@ -4,6 +4,7 @@
 # Licensed under the 3-clause BSD license:
 #
 # Copyright (c) 2014, Alfred Klomp
+# Copyright (c) 2021, Lara <lara@uwu.is>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -29,61 +30,70 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
+# Check prerequisites
+for i in gs wc; do
+    hash "$i" >/dev/null 2>&1 || \
+        (echo "Error: prerequisite $i not found in PATH" >&2; exit 1)
+done
 
 shrink ()
 {
-	gs					\
-	  -q -dNOPAUSE -dBATCH -dSAFER		\
-	  -sDEVICE=pdfwrite			\
-	  -dCompatibilityLevel=1.5		\
-	  -dPDFSETTINGS=/screen			\
-	  -dEmbedAllFonts=true			\
-	  -dSubsetFonts=true			\
-	  -dColorImageDownsampleType=/Bicubic	\
-	  -dColorImageResolution=150		\
-	  -dGrayImageDownsampleType=/Bicubic	\
-	  -dGrayImageResolution=150		\
-	  -dMonoImageDownsampleType=/Bicubic	\
-	  -dMonoImageResolution=150		\
-	  -sOutputFile="$2"			\
-	  "$1"
+    gs \
+      -q -dNOPAUSE -dBATCH -dSAFER \
+      -sDEVICE=pdfwrite \
+      -dCompatibilityLevel=1.5 \
+      -dPDFSETTINGS=/screen \
+      -dEmbedAllFonts=true \
+      -dSubsetFonts=true \
+      -dColorImageDownsampleType=/Bicubic \
+      -dColorImageResolution=150 \
+      -dGrayImageDownsampleType=/Bicubic \
+      -dGrayImageResolution=150 \
+      -dMonoImageDownsampleType=/Bicubic \
+      -dMonoImageResolution=150 \
+      -sOutputFile="$2" \
+      "$1"
 }
 
 check_smaller ()
 {
-	# If $1 and $2 are regular files, we can compare file sizes to
-	# see if we succeeded in shrinking. If not, we copy $1 over $2:
-	if [ ! -f "$1" -o ! -f "$2" ]; then
-		return 0;
-	fi
-	ISIZE="$(echo $(wc -c "$1") | cut -f1 -d\ )"
-	OSIZE="$(echo $(wc -c "$2") | cut -f1 -d\ )"
-	if [ "$ISIZE" -lt "$OSIZE" ]; then
-		echo "Input smaller than output, doing straight copy" >&2
-		cp "$1" "$2"
-	fi
+    # If $1 and $2 are regular files, we can compare file sizes to
+    # see if we succeeded in shrinking. If not, we copy $1 over $2:
+    if [ ! -f "$1" ] || [ ! -f "$2" ]; then
+        return 0;
+    fi
+    ISIZE="$(wc -c "$1" | cut -f1 -d\ )"
+    OSIZE="$(wc -c "$2" | cut -f1 -d\ )"
+    if [ "$ISIZE" -lt "$OSIZE" ]; then
+        echo "Input smaller than output, doing straight copy" >&2
+        cp "$1" "$2"
+    fi
 }
 
 usage ()
 {
-	echo "Reduces PDF filesize by lossy recompressing with Ghostscript."
-	echo "Not guaranteed to succeed, but usually works."
-	echo "  Usage: $1 infile [outfile]"
+    cat <<EOF
+ 
+Usage: $1 infile [outfile]
+
+Reduces PDF filesize by lossy recompressing with Ghostscript.
+Not guaranteed to succeed, but usually works.
+EOF
 }
 
 IFILE="$1"
 
 # Need an input file:
 if [ -z "$IFILE" ]; then
-	usage "$0"
-	exit 1
+    usage "$(basename "$0")"
+    exit 1
 fi
 
 # Output filename defaults to "-" (stdout) unless given:
-if [ ! -z "$2" ]; then
-	OFILE="$2"
+if [ -n "$2" ]; then
+    OFILE="$2"
 else
-	OFILE="-"
+    OFILE="-"
 fi
 
 shrink "$IFILE" "$OFILE" || exit $?
